### PR TITLE
Removed input fields for composing a message in the footer section 

### PR DESCRIPTION
**Pull request by ZSLNgwenya**

### CODE REVIEW

**Review by ofentse-sithole — COMMENTED** [review]
It is good but i think the footer you should decrease the size of it

**Review by ofentse-sithole — COMMENTED** [review]
everything is fine, please move the names of the skills under the rightful icon to make it look professional

**Comment by ZSLNgwenya** [comment]
> everything is fine, please move the names of the skills under the rightful icon to make it look professional

Done, I will push again so you can see the changes

**Comment by yayah0613912091** [comment]
well done, i like your styling

**Comment by ZSLNgwenya** [comment]
> well done, i like your styling

Thanks you!

**Pull request merged**
